train:
  _target_: src.datasets.LJspeechDataset
  part: "train"
  max_audio_length: 8192
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LJspeechDataset
  part: "test"
  limit: 30
  max_audio_length: 8192
  instance_transforms: ${transforms.instance_transforms.inference}
