defaults:
  - model: hifigan
  - model_disc: hifigan_disc
  - writer: wandb
  - metrics: empty
  - datasets: ljspeech
  - dataloader: default
  - transforms: spectrogram
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
gen_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.895
disc_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.895
gen_loss:
  _target_: src.loss.GeneratorLoss
  l_mel: 2.0
  l_feats_ml: 45.0
disc_loss:
  _target_: src.loss.DiscriminatorLoss
trainer:
  n_epochs: 25
  epoch_len: 500
  log_step: 100
  device_tensors: ["audio", "spectrogram"] # which tensors should be on device (ex. GPU)
  from_pretrained: /Users/antonytce/Desktop/hw3/100.pth
  device: auto # device name or "auto"
  override: False  # if True, will override the previous run with the same name
  monitor: "min test_loss" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
